// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	common "github.com/globallogicuki/provider-harbor/config/common"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/thisisnttheway/provider-harbor/apis/cluster/project/v1alpha1"
	v1alpha11 "github.com/thisisnttheway/provider-harbor/apis/cluster/registry/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Replication.
func (mg *Replication) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DestNamespace),
		Extract:      common.ExtractProjectName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DestNamespaceRef,
		Selector:     mg.Spec.ForProvider.DestNamespaceSelector,
		To: reference.To{
			List:    &v1alpha1.ProjectList{},
			Managed: &v1alpha1.Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DestNamespace")
	}
	mg.Spec.ForProvider.DestNamespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DestNamespaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.RegistryID),
		Extract:      common.ExtractRegistryID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.RegistryIDRef,
		Selector:     mg.Spec.ForProvider.RegistryIDSelector,
		To: reference.To{
			List:    &v1alpha11.RegistryList{},
			Managed: &v1alpha11.Registry{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RegistryID")
	}
	mg.Spec.ForProvider.RegistryID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RegistryIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DestNamespace),
		Extract:      common.ExtractProjectName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DestNamespaceRef,
		Selector:     mg.Spec.InitProvider.DestNamespaceSelector,
		To: reference.To{
			List:    &v1alpha1.ProjectList{},
			Managed: &v1alpha1.Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DestNamespace")
	}
	mg.Spec.InitProvider.DestNamespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DestNamespaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.RegistryID),
		Extract:      common.ExtractRegistryID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.RegistryIDRef,
		Selector:     mg.Spec.InitProvider.RegistryIDSelector,
		To: reference.To{
			List:    &v1alpha11.RegistryList{},
			Managed: &v1alpha11.Registry{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RegistryID")
	}
	mg.Spec.InitProvider.RegistryID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RegistryIDRef = rsp.ResolvedReference

	return nil
}
